language: go
sudo: false
go:
  - 1.6.3
  - 1.7.1
  - tip
os:
  - linux
  - osx
script:
  - go test -coverprofile=coverage.txt -covermode=atomic
install:
  - go get -v ./...
after_success:
  - bash <(curl -s https://codecov.io/bash)
